# Generated by Django 6.0 on 2026-01-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_remove_profile_skills_project_github_project_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
