# Generated by Django 6.0 on 2026-01-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Other', 'Other')], default='Other', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveIntegerField(help_text='0–100'),
        ),
    ]
